name: Merge upstream branches
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: nixpkgs-final
      - uses: actions/checkout@v2
        with:
          path: nixpkgs-original
          repository: NixOS/nixpkgs
          ref: nixpkgs-unstable
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          persist-credentials: true
      - name: Install nix
        uses: miuirussia/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: Merge upstream
        run: |
          pushd ./nixpkgs-original
          git apply -v ../nixpkgs-final/patches/*.patch
          popd
          rsync -avu --delete ./nixpkgs-original/doc/ ./nixpkgs-final/doc
          rsync -avu --delete ./nixpkgs-original/lib/ ./nixpkgs-final/lib
          rsync -avu --delete ./nixpkgs-original/maintainers/ ./nixpkgs-final/maintainers
          rsync -avu --delete ./nixpkgs-original/nixos/ ./nixpkgs-final/nixos
          rsync -avu --delete ./nixpkgs-original/pkgs/ ./nixpkgs-final/pkgs
          cp -f ./nixpkgs-original/{.editorconfig,.gitattributes,.gitignore,.version,CONTRIBUTING.md,COPYING,README.md,default.nix,flake.nix} ./nixpkgs-final
          $(nix-build ./nixpkgs-final -A pkgs.tree-sitter.passthru.updater.update-all-grammars)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        run: |
          cd ./nixpkgs-final

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git add .
          git commit -m "Automatic merge from NixOS/nixpkgs"
          git push origin nixpkgs-unstable
